version: "3"

vars:
  GOIMPORTS_VERSION: latest
  GOLANGCI_LINT_VERSION: v2.12.2

tasks:
  default:
    cmds:
      - task --list-all

  # ./data should be created
  start:runner:
    desc: "создает папку для маунта наделяет правами регается в контрол плейне и запускает раннер с сайдкаром через который раннер подключается к кп по впн шлюзу"
    cmds:
      - mkdir -p ./data
      - chown 1000:1000 ./data
      - cargo run runner start --cp-address-runner cp.viskoz.dev:9096 --join-secret none --host-data-path "${PWD}/data"

  player:connect:
    desc: "обращается к кп за пресайн реквестом для регистрации в меш сети, регается в меш сети"
    cmds:
      - mkdir -p ./data
      - chown 1000:1000 ./data
      - cargo run user connect --cp-address-user cp.viskoz.dev:9095 --join-secret none

  release:
    cmds:
      # - rustup target add x86_64-pc-windows-gnu
      #- sudo pacman -S mingw-w64-gcc
      - cargo build --release
      - cargo build --release --target x86_64-pc-windows-gnu

  upd:desktop:
    cmds:
      - cp /home/end1essrage/Projects/MGS/cli/target/release/viskoz-cli    /home/end1essrage/Projects/MGS/desktop/src-tauri/binaries/viskoz-cli-x86_64-unknown-linux-gnu
      - cp /home/end1essrage/Projects/MGS/cli/target/x86_64-pc-windows-gnu/release/viskoz-cli.exe    /home/end1essrage/Projects/MGS/desktop/src-tauri/binaries/viskoz-cli-x86_64-pc-windows-msvc.exe